// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class CallStatement extends UserAction<java.lang.String>
{
	private final java.lang.String Routine;
	private final java.lang.String Kind;
	private final java.lang.String Parameters;
	private final java.lang.String Dialect;

	public CallStatement(
		IContext context,
		java.lang.String _routine,
		java.lang.String _kind,
		java.lang.String _parameters,
		java.lang.String _dialect
	)
	{
		super(context);
		this.Routine = _routine;
		this.Kind = _kind;
		this.Parameters = _parameters;
		this.Dialect = _dialect;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		return owid.RoutineCall.statement(Routine, Kind, Parameters, Dialect);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CallStatement";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
