// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class CardSpec extends UserAction<java.lang.String>
{
	private final java.lang.String ChartType;
	private final java.lang.String XField;
	private final java.lang.String YField;
	private final java.lang.String SeriesField;
	private final java.lang.String Agg;
	private final java.lang.Boolean XIsMeasure;
	private final java.lang.Long SeriesCount;
	private final java.lang.Long Height;

	public CardSpec(
		IContext context,
		java.lang.String _chartType,
		java.lang.String _xField,
		java.lang.String _yField,
		java.lang.String _seriesField,
		java.lang.String _agg,
		java.lang.Boolean _xIsMeasure,
		java.lang.Long _seriesCount,
		java.lang.Long _height
	)
	{
		super(context);
		this.ChartType = _chartType;
		this.XField = _xField;
		this.YField = _yField;
		this.SeriesField = _seriesField;
		this.Agg = _agg;
		this.XIsMeasure = _xIsMeasure;
		this.SeriesCount = _seriesCount;
		this.Height = _height;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		String type = ChartType == null ? "Line" : ChartType;
		boolean hasSeries = SeriesField != null && !SeriesField.trim().isEmpty();
		String agg = Agg == null ? "NoAgg" : Agg;
		
		java.util.function.Function<String, String> esc = t ->
		        t == null ? "" : t.replace("\\", "\\\\").replace("\"", "\\\"");
		
		String yTitle = "Count".equals(agg) && (YField == null || YField.trim().isEmpty())
		        ? "count"
		        : ("NoAgg".equals(agg) ? esc.apply(YField)
		                               : agg.toLowerCase() + " of " + esc.apply(YField));
		
		// The board's palette, so a chart the user assembled still looks like the rest
		// of the page rather than like Vega's defaults.
		String RANGE = "[\"#1d2d3d\",\"#416180\",\"#597ea3\",\"#749dc4\",\"#94bce3\","
		             + "\"#b8712f\",\"#a9a9ad\",\"#6c8fae\",\"#2c4763\",\"#c9a227\"]";
		String CONFIG =
		    "\"config\":{\"font\":\"Barlow\",\"view\":{\"stroke\":\"transparent\"},"
		  + "\"axis\":{\"labelFont\":\"Barlow\",\"labelFontSize\":10,\"labelColor\":\"#6c6f72\","
		  + "\"domainColor\":\"#dededf\",\"tickColor\":\"#dededf\",\"gridColor\":\"#ebebec\","
		  + "\"titleFont\":\"Barlow Condensed\",\"titleFontSize\":11,\"titleColor\":\"#6c6f72\","
		  + "\"titleFontWeight\":400},"
		  // symbolLimit is not cosmetic: splitting by country gives 200-odd series and
		  // Vega warns and truncates on its own. Capping it says the same thing on
		  // purpose, and the chart stays readable.
		  + "\"legend\":{\"labelFont\":\"Barlow\",\"labelFontSize\":10,\"labelColor\":\"#6c6f72\","
		  + "\"title\":null,\"symbolStrokeWidth\":2,"
		  + "\"orient\":\"bottom\",\"direction\":\"horizontal\"},"
		  + "\"range\":{\"category\":" + RANGE + ",\"heatmap\":[\"#fcfdfe\",\"#b0cae1\",\"#4f74a0\",\"#0e161d\"]}}";
		
		long h = Height == null || Height <= 0 ? 260L : Height;
		StringBuilder b = new StringBuilder();
		b.append("{\"$schema\":\"https://vega.github.io/schema/vega-lite/v6.json\",")
		 .append("\"data\":{\"name\":\"table\"},\"background\":null,")
		 .append("\"width\":\"container\",\"height\":").append(h).append(",")
		 .append(CONFIG).append(",");
		
		if ("Number".equals(type)) {
		    // A KPI is a text mark, which is the whole chart: one datum, one number,
		    // sized to be read from across the room.
		    b.append("\"mark\":{\"type\":\"text\",\"font\":\"Barlow Condensed\",\"fontSize\":64,")
		     .append("\"fontWeight\":600,\"color\":\"#1d2d3d\",\"align\":\"center\",\"baseline\":\"middle\"},")
		     .append("\"encoding\":{\"text\":{\"field\":\"y\",\"type\":\"quantitative\",")
		     .append("\"format\":\",.4~s\"}}}");
		    return b.toString();
		}
		
		// Above a dozen series the legend stops being a key and becomes a wall, so it
		// goes away and the card's own caption says how many there were instead.
		boolean legend = SeriesCount != null && SeriesCount > 0 && SeriesCount <= 12;
		String colour = hasSeries
		        ? ("\"color\":{\"field\":\"s\",\"type\":\"nominal\""
		           + (legend ? "" : ",\"legend\":null") + "},")
		        : "";
		
		if ("Heatmap".equals(type)) {
		    b.append("\"mark\":{\"type\":\"rect\"},\"encoding\":{")
		     .append("\"x\":{\"field\":\"x\",\"type\":\"nominal\",\"axis\":{\"title\":\"")
		     .append(esc.apply(XField)).append("\",\"labelAngle\":0}},")
		     .append("\"y\":{\"field\":\"s\",\"type\":\"nominal\",\"axis\":{\"title\":\"")
		     .append(esc.apply(SeriesField)).append("\"}},")
		     .append("\"color\":{\"field\":\"y\",\"type\":\"quantitative\",\"title\":\"")
		     .append(yTitle).append("\"},")
		     .append("\"tooltip\":[{\"field\":\"x\"},{\"field\":\"s\"},")
		     .append("{\"field\":\"y\",\"type\":\"quantitative\",\"format\":\",.4~g\"}]}}");
		    return b.toString();
		}
		
		// A bar chart over a text column is categorical; a bar chart over a number --
		// a year, an age -- is not, and forcing it to nominal turns 153 years into 153
		// tick labels drawn on top of each other. The column decides, not the mark.
		String xType = XIsMeasure ? "quantitative" : "nominal";
		String mark;
		switch (type) {
		    case "Bar":     mark = "{\"type\":\"bar\"}"; break;
		    case "Area":    mark = "{\"type\":\"area\",\"opacity\":0.85}"; break;
		    case "Scatter": mark = "{\"type\":\"circle\",\"size\":60,\"opacity\":0.7}"; break;
		    default:        mark = "{\"type\":\"line\",\"strokeWidth\":1.6,\"point\":false}";
		}
		
		b.append("\"mark\":").append(mark).append(",\"encoding\":{")
		 .append("\"x\":{\"field\":\"x\",\"type\":\"").append(xType).append("\",")
		 .append("\"scale\":{\"nice\":false").append("quantitative".equals(xType) ? ",\"zero\":false" : "")
		 .append("},\"axis\":{\"title\":\"").append(esc.apply(XField)).append("\"")
		 // Categorical axes get as many labels as there are categories unless told
		 // otherwise; greedy dropping keeps the ones that fit.
		 .append(",\"labelOverlap\":\"greedy\"")
		 .append("Bar".equals(type) ? ",\"labelAngle\":0" : "").append("}},")
		 .append("\"y\":{\"field\":\"y\",\"type\":\"quantitative\",\"scale\":{\"zero\":")
		 .append("Bar".equals(type) || "Area".equals(type) ? "true" : "false")
		 .append(",\"nice\":false},\"axis\":{\"title\":\"").append(yTitle).append("\"}},")
		 .append(colour)
		 .append("\"tooltip\":[{\"field\":\"x\"},")
		 .append(hasSeries ? "{\"field\":\"s\"}," : "")
		 .append("{\"field\":\"y\",\"type\":\"quantitative\",\"format\":\",.4~g\"}]}}");
		return b.toString();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CardSpec";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
