// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class CardSql extends UserAction<java.lang.String>
{
	private final java.lang.String Url;
	private final java.lang.String ChartType;
	private final java.lang.String XField;
	private final java.lang.String YField;
	private final java.lang.String SeriesField;
	private final java.lang.String Agg;
	private final java.lang.String FilterField;
	private final java.lang.Long RowLimit;
	private final java.lang.String AllowedFields;

	public CardSql(
		IContext context,
		java.lang.String _url,
		java.lang.String _chartType,
		java.lang.String _xField,
		java.lang.String _yField,
		java.lang.String _seriesField,
		java.lang.String _agg,
		java.lang.String _filterField,
		java.lang.Long _rowLimit,
		java.lang.String _allowedFields
	)
	{
		super(context);
		this.Url = _url;
		this.ChartType = _chartType;
		this.XField = _xField;
		this.YField = _yField;
		this.SeriesField = _seriesField;
		this.Agg = _agg;
		this.FilterField = _filterField;
		this.RowLimit = _rowLimit;
		this.AllowedFields = _allowedFields;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		java.util.Set<String> ok = new java.util.HashSet<>();
		for (String f : AllowedFields.split(",")) {
		    String n = f.trim();
		    if (!n.isEmpty()) {
		        ok.add(n);
		    }
		}
		
		// A column name is quoted, never escaped-and-hoped: it has already been proved
		// to exist by DESCRIBE, and anything else throws rather than reaching DuckDB.
		java.util.function.Function<String, String> col = name -> {
		    String n = name == null ? "" : name.trim();
		    if (n.isEmpty()) {
		        throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
		                "This chart needs a field that has not been chosen yet.");
		    }
		    if (!ok.contains(n)) {
		        throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
		                "'" + n + "' is not a column of this table.");
		    }
		    return "\"" + n.replace("\"", "\"\"") + "\"";
		};
		
		String type = ChartType == null ? "Line" : ChartType;
		String agg  = Agg == null ? "NoAgg" : Agg;
		boolean aggregated = !"NoAgg".equals(agg);
		
		java.util.function.Function<String, String> value = c -> {
		    switch (agg) {
		        case "Sum":   return "sum(" + c + ")";
		        case "Avg":   return "avg(" + c + ")";
		        case "Min":   return "min(" + c + ")";
		        case "Max":   return "max(" + c + ")";
		        case "Count": return "count(" + c + ")";
		        default:      return c;
		    }
		};
		
		long limit = RowLimit == null || RowLimit <= 0 ? 5000L : Math.min(RowLimit, 50000L);
		String from = " FROM read_parquet('" + Url.replace("'", "''") + "')";
		
		// The filter is always present and always inert when empty, which is what lets
		// one statement serve the filtered and unfiltered card. Cast to VARCHAR so a
		// numeric column and a typed-in year compare as the same thing.
		String where = "";
		if (FilterField != null && !FilterField.trim().isEmpty()) {
		    where = " WHERE ({filterval} = '' OR CAST(" + col.apply(FilterField)
		          + " AS VARCHAR) = {filterval})";
		}
		
		StringBuilder inner = new StringBuilder();
		
		if ("Number".equals(type)) {
		    // No axes at all: one row, one number. Count is the only aggregate that
		    // means anything without a column, so it is allowed to have none.
		    String y = "Count".equals(agg) && (YField == null || YField.trim().isEmpty())
		             ? "count(*)"
		             : value.apply(col.apply(YField));
		    inner.append("SELECT ").append(y).append(" AS y").append(from).append(where);
		} else if ("Heatmap".equals(type)) {
		    // Two dimensions and a colour: x across, series down, value in the cell.
		    inner.append("SELECT ").append(col.apply(XField)).append(" AS x, ")
		         .append(col.apply(SeriesField)).append(" AS s, ")
		         .append(value.apply(col.apply(YField))).append(" AS y")
		         .append(from).append(where)
		         .append(" GROUP BY 1, 2 ORDER BY 1, 2");
		} else if ("Scatter".equals(type)) {
		    // Aggregated, the split field IS the grain -- one point per country rather
		    // than one per country-year, which is the whole reason to aggregate a
		    // scatter. Unaggregated it is the raw rows and the split is just colour.
		    boolean hasSeries = SeriesField != null && !SeriesField.trim().isEmpty();
		    if (aggregated && hasSeries) {
		        inner.append("SELECT ").append(col.apply(SeriesField)).append(" AS s, ")
		             .append(value.apply(col.apply(XField))).append(" AS x, ")
		             .append(value.apply(col.apply(YField))).append(" AS y")
		             .append(from).append(where).append(" GROUP BY 1 ORDER BY 1");
		    } else {
		        inner.append("SELECT ").append(col.apply(XField)).append(" AS x, ")
		             .append(col.apply(YField)).append(" AS y");
		        if (hasSeries) {
		            inner.append(", ").append(col.apply(SeriesField)).append(" AS s");
		        }
		        inner.append(from).append(where);
		    }
		} else {
		    // Line, Bar, Area: a key across the bottom, a value up the side, and an
		    // optional second key that becomes the series.
		    boolean hasSeries = SeriesField != null && !SeriesField.trim().isEmpty();
		    inner.append("SELECT ").append(col.apply(XField)).append(" AS x");
		    if (hasSeries) {
		        inner.append(", ").append(col.apply(SeriesField)).append(" AS s");
		    }
		    inner.append(", ").append(value.apply(col.apply(YField))).append(" AS y")
		         .append(from).append(where);
		    if (aggregated) {
		        inner.append(hasSeries ? " GROUP BY 1, 2" : " GROUP BY 1");
		    }
		    inner.append(hasSeries ? " ORDER BY 1, 2" : " ORDER BY 1");
		}
		
		inner.append(" LIMIT ").append(limit);
		
		// struct_pack over the projected row rather than to_json(t) so the JSON keys
		// are x/s/y whatever the columns were called -- the spec is written against
		// those three names and never has to know.
		String pack = "Scatter".equals(type) || "Line".equals(type) || "Bar".equals(type)
		           || "Area".equals(type) || "Heatmap".equals(type)
		        ? (inner.indexOf(" AS s") >= 0
		              ? "struct_pack(x := t.x, s := t.s, y := t.y)"
		              : "struct_pack(x := t.x, y := t.y)")
		        : "struct_pack(y := t.y)";
		
		// The distinct series count travels with the data because the spec needs it
		// and cannot work it out: a split by country is 200-odd series, and a legend
		// with 200 entries is not a legend. CardSpec turns it off above a threshold
		// rather than letting Vega truncate it and warn.
		String seriesCount = inner.indexOf(" AS s") >= 0 ? "count(DISTINCT t.s)" : "0";
		return "SELECT coalesce(to_json(list(" + pack + ")), '[]') AS j, count(*) AS n, "
		     + seriesCount + " AS s FROM (" + inner + ") t";

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CardSql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
