// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Key extends UserAction<java.lang.String>
{
	private final java.lang.String Uri;
	private final java.lang.String KeyField;

	public Key(
		IContext context,
		java.lang.String _uri,
		java.lang.String _keyField
	)
	{
		super(context);
		this.Uri = _uri;
		this.KeyField = _keyField;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		return owid.ODataQueryParser.key(Uri, KeyField);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Key";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
