// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Parse extends UserAction<IMendixObject>
{
	private final java.lang.String Uri;
	private final java.lang.String Columns;
	private final java.lang.String Dialect;
	private final java.lang.Long MaxTop;
	private final java.lang.Long DefaultTop;
	private final java.lang.String DefaultOrderBy;
	private final java.lang.String KeyField;
	private final java.lang.Boolean RejectUnsupported;

	public Parse(
		IContext context,
		java.lang.String _uri,
		java.lang.String _columns,
		java.lang.String _dialect,
		java.lang.Long _maxTop,
		java.lang.Long _defaultTop,
		java.lang.String _defaultOrderBy,
		java.lang.String _keyField,
		java.lang.Boolean _rejectUnsupported
	)
	{
		super(context);
		this.Uri = _uri;
		this.Columns = _columns;
		this.Dialect = _dialect;
		this.MaxTop = _maxTop;
		this.DefaultTop = _defaultTop;
		this.DefaultOrderBy = _defaultOrderBy;
		this.KeyField = _keyField;
		this.RejectUnsupported = _rejectUnsupported;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		return owid.QueryObject.parse(getContext(), Uri, Columns, Dialect,
		        MaxTop, DefaultTop, DefaultOrderBy, KeyField, RejectUnsupported);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Parse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
