// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class PathKey extends UserAction<java.lang.String>
{
	private final java.lang.String Uri;

	public PathKey(
		IContext context,
		java.lang.String _uri
	)
	{
		super(context);
		this.Uri = _uri;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		if (Uri == null) {
		    return "";
		}
		int q = Uri.indexOf('?');
		String path = q < 0 ? Uri : Uri.substring(0, q);
		java.util.regex.Matcher m = java.util.regex.Pattern
		        .compile("\\(\\s*(?:[A-Za-z_][A-Za-z0-9_]*\\s*=\\s*)?'((?:[^']|'')*)'\\s*\\)\\s*$")
		        .matcher(path);
		if (!m.find()) {
		    return "";
		}
		String raw = m.group(1).replace("''", "'");
		return java.net.URLDecoder.decode(raw, java.nio.charset.StandardCharsets.UTF_8);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PathKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
