// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class RefreshOwidData extends UserAction<java.lang.Long>
{
	private final java.lang.String BaseUrl;
	private final java.lang.Long YearFrom;
	private final java.lang.Long YearTo;

	public RefreshOwidData(
		IContext context,
		java.lang.String _baseUrl,
		java.lang.Long _yearFrom,
		java.lang.Long _yearTo
	)
	{
		super(context);
		this.BaseUrl = _baseUrl;
		this.YearFrom = _yearFrom;
		this.YearTo = _yearTo;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		// Resources land in the deployment's resources folder; MxBuild copies them.
		java.io.File resDir = com.mendix.core.Core.getConfiguration().getResourcesPath();
		java.io.File sqlFile = new java.io.File(resDir, "owid_extract.sql");
		java.io.File isoFile = new java.io.File(resDir, "iso3166_numeric.csv");
		
		if (!sqlFile.exists() || !isoFile.exists()) {
		    throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
		        "OWID resources missing under " + resDir.getAbsolutePath());
		}
		
		String script = new String(
		    java.nio.file.Files.readAllBytes(sqlFile.toPath()),
		    java.nio.charset.StandardCharsets.UTF_8);
		
		script = script
		    .replace("${BASE}", BaseUrl)
		    .replace("${ISO_CSV}", isoFile.getAbsolutePath().replace("\\", "/"))
		    .replace("${Y0}", String.valueOf(YearFrom))
		    .replace("${Y1}", String.valueOf(YearTo));
		
		// Strip line comments before splitting, so a ';' inside a comment cannot end a
		// statement. No string literal in this script contains ';'.
		StringBuilder stripped = new StringBuilder();
		for (String line : script.split("\n")) {
		    int c = line.indexOf("--");
		    stripped.append(c >= 0 ? line.substring(0, c) : line).append("\n");
		}
		
		java.util.List<String> statements = new java.util.ArrayList<String>();
		for (String part : stripped.toString().split(";")) {
		    if (part.trim().length() > 0) statements.add(part.trim());
		}
		if (statements.isEmpty()) {
		    throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
		        "owid_extract.sql contained no statements");
		}
		
		final String[] measures = {"Pop", "Gdp", "Le", "Cm", "En", "Co2", "Fe", "Kc", "Sc"};
		com.mendix.systemwideinterfaces.core.IContext ctx = getContext();
		
		// Clear the previous load first. Observation carries a reference to Country, so
		// it goes first and the association cannot dangle. Deleted in slices so a full
		// reload never holds every row in memory at once.
		for (String ent : new String[]{"Owid.Observation", "Owid.Country"}) {
		    while (true) {
		        java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> old =
		            com.mendix.core.Core.createXPathQuery("//" + ent)
		                .setAmount(5000)
		                .execute(ctx);
		        if (old.isEmpty()) break;
		        com.mendix.core.Core.delete(ctx, old);
		    }
		}
		
		java.util.Map<String, com.mendix.systemwideinterfaces.core.IMendixObject> countries =
		    new java.util.HashMap<String, com.mendix.systemwideinterfaces.core.IMendixObject>();
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> batch =
		    new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject>();
		long rows = 0L;
		
		Class.forName("org.duckdb.DuckDBDriver");
		// jdbc:duckdb: with no path is a private in-memory database; nothing touches disk.
		java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:duckdb:");
		try {
		    java.sql.Statement st = conn.createStatement();
		    try {
		        st.execute("INSTALL httpfs");
		        // Everything but the last statement builds views; the last is the query.
		        for (int i = 0; i < statements.size() - 1; i++) {
		            st.execute(statements.get(i));
		        }
		        java.sql.ResultSet rs = st.executeQuery(statements.get(statements.size() - 1));
		        try {
		            while (rs.next()) {
		                String cname  = rs.getString(1);
		                String code   = rs.getString(2);
		                int    isoNum = rs.getInt(3);
		                String region = rs.getString(4);
		
		                com.mendix.systemwideinterfaces.core.IMendixObject country = countries.get(cname);
		                if (country == null) {
		                    country = com.mendix.core.Core.instantiate(ctx, "Owid.Country");
		                    country.setValue(ctx, "Name", cname);
		                    country.setValue(ctx, "Code", code);
		                    country.setValue(ctx, "IsoNumeric", Integer.valueOf(isoNum));
		                    country.setValue(ctx, "Region", region);
		                    com.mendix.core.Core.commit(ctx, country);
		                    countries.put(cname, country);
		                }
		
		                com.mendix.systemwideinterfaces.core.IMendixObject obs =
		                    com.mendix.core.Core.instantiate(ctx, "Owid.Observation");
		                int yr = rs.getInt(5);
		                obs.setValue(ctx, "Year", Integer.valueOf(yr));
		                obs.setValue(ctx, "CountryName", cname);
		                // Synthetic key: Observation is keyed on country AND year, and
		                // an OData key must be a single unique attribute.
		                obs.setValue(ctx, "RowKey", cname + "|" + yr);
		                obs.setValue(ctx, "IsoNumeric", Integer.valueOf(isoNum));
		                obs.setValue(ctx, "Region", region);
		                obs.setValue(ctx, "Owid.Observation_Country", country.getId());
		
		                // Measures start at column 6, in the order the final SELECT lists
		                // them. A missing value stays null: OWID genuinely has no CO2 for
		                // 1960, and a 0 there would read as a real measurement.
		                for (int c = 0; c < measures.length; c++) {
		                    java.math.BigDecimal v = rs.getBigDecimal(6 + c);
		                    if (rs.wasNull()) v = null;
		                    obs.setValue(ctx, measures[c], v);
		                }
		
		                batch.add(obs);
		                rows++;
		                if (batch.size() >= 1000) {
		                    com.mendix.core.Core.commit(ctx, batch);
		                    batch.clear();
		                }
		            }
		        } finally {
		            rs.close();
		        }
		    } finally {
		        st.close();
		    }
		} finally {
		    conn.close();
		}
		
		if (!batch.isEmpty()) com.mendix.core.Core.commit(ctx, batch);
		
		return Long.valueOf(rows);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RefreshOwidData";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
