// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package owid.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class UrlStatus extends UserAction<java.lang.Long>
{
	private final java.lang.String Url;

	public UrlStatus(
		IContext context,
		java.lang.String _url
	)
	{
		super(context);
		this.Url = _url;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		java.net.HttpURLConnection c = null;
		try {
		    c = (java.net.HttpURLConnection) java.net.URI.create(Url).toURL().openConnection();
		    c.setRequestMethod("HEAD");
		    c.setConnectTimeout(8000);
		    c.setReadTimeout(8000);
		    c.setInstanceFollowRedirects(true);
		    return java.lang.Long.valueOf(c.getResponseCode());
		} catch (java.lang.Exception e) {
		    // Unreachable is not the same as absent, and the caller distinguishes them.
		    return java.lang.Long.valueOf(0L);
		} finally {
		    if (c != null) {
		        c.disconnect();
		    }
		}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UrlStatus";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
