#!/bin/sh
# Originally generated by 'mxcli init'; edited to build from source. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: obtain mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~88 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# THIS PROJECT TRACKS ako/mxcli main, BUILT FROM SOURCE — not the mendixlabs
# nightly. `go install ...@latest` does not work: the ANTLR parser is not
# committed, so the build needs `make grammar` first, which needs a JVM and the
# pinned antlr4-tools. If any of that is unavailable we fall back to the
# nightly binary so a session is never left with no mxcli at all.
#
#   MXCLI_REPO    git URL to build from      (default: https://github.com/ako/mxcli)
#   MXCLI_REV     revision to build          (default: main)
#   MXCLI_TAG     nightly tag for fallback   (default: nightly)
#   MXCLI_NO_BUILD=1  skip the source build and go straight to the fallback
set -e

MPR='OwidExplorer.mpr'
REPO="${MXCLI_REPO:-https://github.com/ako/mxcli}"
REV="${MXCLI_REV:-main}"
TAG="${MXCLI_TAG:-nightly}"
ANTLR_VERSION=4.13.2
ANTLR_TOOLS_VERSION=0.2.2

download_nightly() {
  os=$(uname -s | tr 'A-Z' 'a-z')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) arch=$(uname -m) ;;
  esac
  url="https://github.com/mendixlabs/mxcli/releases/download/${TAG}/mxcli-${os}-${arch}"
  echo "Falling back to prebuilt ${TAG} for ${os}/${arch}..."
  if ! curl -fsSL -o ./mxcli "$url"; then
    echo "Could not download mxcli from ${url}." >&2
    echo "Fetch it manually, or set MXCLI_TAG to a released version." >&2
    return 1
  fi
  chmod +x ./mxcli
}

build_from_source() {
  [ -n "$MXCLI_NO_BUILD" ] && return 1
  command -v go >/dev/null 2>&1 || { echo "no Go toolchain; skipping source build" >&2; return 1; }
  command -v java >/dev/null 2>&1 || { echo "no JVM (ANTLR needs one); skipping source build" >&2; return 1; }

  src="${MXCLI_SRC_DIR:-${TMPDIR:-/tmp}/mxcli-src}"
  echo "Building mxcli from ${REPO}@${REV} (this takes a few minutes)..."
  if [ -d "$src/.git" ]; then
    git -C "$src" fetch --depth 1 origin "$REV" >/dev/null 2>&1 || return 1
    git -C "$src" checkout -q FETCH_HEAD || return 1
  else
    rm -rf "$src"
    git clone --depth 1 --branch "$REV" "$REPO" "$src" >/dev/null 2>&1 || return 1
  fi

  # The generated ANTLR parser is not committed; regenerate it with the pinned
  # generator. antlr4-tools downloads the jar on first run, so this needs network.
  if ! command -v antlr4 >/dev/null 2>&1; then
    pip install --quiet "antlr4-tools==${ANTLR_TOOLS_VERSION}" >/dev/null 2>&1 || return 1
  fi
  ANTLR4_TOOLS_ANTLR_VERSION="$ANTLR_VERSION"; export ANTLR4_TOOLS_ANTLR_VERSION
  ( cd "$src" && make grammar && make build ) >/dev/null 2>&1 || return 1

  cp "$src/bin/mxcli" ./mxcli && chmod +x ./mxcli
  echo "Built mxcli $(./mxcli --version 2>/dev/null | head -1)"
}

if [ ! -x ./mxcli ]; then
  build_from_source || download_nightly || exit 1
fi

# DuckDB is a declared Maven dependency (Owid module -> Java dependencies) and
# its jar is committed under vendorlib/, so a fresh clone builds as-is. This is
# only a repair step for a checkout where vendorlib/ is incomplete.
./mxcli sync-java-deps -p "$MPR" >/dev/null 2>&1 || true

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
